### ISSUE TITLE
sed - expected context address on macOS

### ISSUE THREAD

**Issue by peacememories** [Rahix/avr-device#24]
Hi, I've got another "this only works with gnu-sed" situation.
The issue is on this line:
https://github.com/Rahix/avr-device/blob/a2c84372a87bbfa9f71029da4fdb7268f6dc6158/Makefile#L48

`,+3c` is a gnu-sed specific command, partially explained here, i guess? https://stackoverflow.com/questions/26124650/sed-use-expected-context-address

To be quite honest I don't know what the `c` does so I'm not sure how to change this so it works on any `sed`. Maybe it's worth thinking about replacing the `sed` calls with `awk` calls altogether since `awk` seems to work the same on different posix systems.

**Comment by Rahix** [comment]
Yes, this might be a good idea!  I just happened to know `sed` much better so that's what I chose ...

Another thing which should be mentioned is the fact that all this logic will need to be changed quite a bit once more because upstream `svd2rust` broke our stuff again ... Haven't had time to look at the details yet, though it seems to be quite a big change on their side.  Was reported in #23.

**Comment by Rahix** [comment]
By the way, nice to see you again :)

**Comment by peacememories** [comment]
I'm glad to be back :) Although I seem to have shot my rust-avr installation... again...^^ Seems to happen everytime I take a break from the project^^

**Comment by Rahix** [comment]
Replaced the `sed` invocation in the above commit.  Maybe this works for you now?  Sorry for the delay ...

**Comment by Rahix** [comment]
Closing for now.  If this is still a problem, we can reopen this issue!
